#!/usr/local/bin/ansible-playbook --inventory=inventory

- name: ' Konductor UPI '
  hosts: local
  vars:
    module: "build"
    state_provider: "local"
    tf_module_path: "{{ dir_terraform }}/shaman"
    vars_module_path: "{{ dir_terraform }}"
    ansible_name_module: " Konductor | UPI | {{ module }}"
  vars_files:
    - vars/global.yml

  tasks:

    ####### Symlinks
    - name: '{{ ansible_name_module }} | variable | Create variable symlink'
      file:
        src: "{{ tf_module_path }}/variables.tf"
        dest: "{{ item }}"
        state: link
      loop:
        - "{{ tf_module_path }}/elb/variables.tf"
        - "{{ tf_module_path }}/control-plane/variables.tf"

    ####### Terraform Init
    - name: '{{ ansible_name_module }} | shell | terraform init'
      shell: terraform init
      loop:
        - "{{ tf_module_path }}/elb"
        - "{{ tf_module_path }}/control-plane"

    ####### Terraform Apply
    - name: '{{ ansible_name_module }} | terraform | apply'
      terraform:
        project_path: "{{ item }}"
        variables_file: "{{ vars_module_path }}/global.tfvars"
        state: present
      loop:
        - "{{ tf_module_path }}/elb"
        - "{{ tf_module_path }}/control-plane"
      register: tf_output
